2 Case Studies used to implement RAII Framework
radicalventures/RAIS-Framework pull request #1
Opened 2023-10-30 16:58 UTC by Viky397

Adding two case studies that implement the RAII Framework in real-world scenarios.

2023-10-30 20:09 UTC, radicalventures requested changes
The framework title has changed - please replace the file title with "RAIS Framework..."

2023-11-13 19:18 UTC, Viky397 commented
The names of the files have been changed to reflect the new framework title.

2023-11-13 20:29 UTC, radicalventures approved these changes

2023-11-13 20:30 UTC, merged

2023-11-13 20:50 UTC, radicalventures commented
Thank you, Veronica. I've accepted and merged.

Much appreciated!
Leah

--
*Leah Morris*
*Calendar <https://calendly.com/leahmorris/30min> | LinkedIn
<https://ca.linkedin.com/in/leahelizabethmorris> | Website
<https://radical.vc/> | M: 902-719-4147*
[image: Radical Ventures | Crunchbase]


On Mon, Nov 13, 2023 at 2:18 PM Veronica Chatrath ***@***.***>
wrote:

> The names of the files have been changed to reflect the new framework
> title.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/radicalventures/RAIS-Framework/pull/1#issuecomment-1808868163>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCJJBHUHW3R54M7YKJ6GTALYEJXCDAVCNFSM6AAAAAA6WLGTRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBYHA3DQMJWGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>